name: Build
on: [push]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - run: yarn install
      - run: yarn test
      - run: yarn make
      - name: get version
        run: |
          VERSION="$(node -p "require('./package.json').version")"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        id: version
      - uses: actions/upload-artifact@v3
        with:
          name: elemntary-linux-${{ steps.version.outputs.VERSION }}-bundle
          path: |
            out/make/zip/linux/x64/*zip
          if-no-files-found: error
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - run: yarn install
      - run: yarn test
      - run: yarn make
      - name: get version
        run: |
          VERSION="$(node -p "require('./package.json').version")"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        id: version
      - uses: actions/upload-artifact@v3
        with:
          name: elemntary-macos-${{ steps.version.outputs.VERSION }}-bundle
          path: |
            out/make/zip/darwin/x64/*zip
          if-no-files-found: error
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - run: yarn install
      - run: yarn test
      - run: yarn make
      - name: get version
        run: |
          $VERSION=(node -p "require('./package.json').version")
          Write-Output "VERSION=$VERSION" | Out-File -FilePath $env:GITHUB_OUTPUT
        id: version
      - uses: actions/upload-artifact@v3
        with:
          name: elemntary-windows-${{ steps.version.outputs.VERSION }}-bundle
          path: out/make/zip/win32/x64/*zip
          if-no-files-found: error
